import { EquipmentItem } from '../types';

export const EQUIPMENT_CATALOG: EquipmentItem[] = [
  {
    id: 'eq-tv-samsung-55',
    slug: 'samsung-crystal-uhd-55',
    name: 'Televisor Samsung Crystal UHD 55"',
    brand: 'Samsung',
    model: 'Crystal UHD 4K (Série AU/BU)',
    category: 'domestico',
    categoryName: 'Linha Doméstica',
    serviceSlug: 'reparacao-de-televisores',
    description: 'Smart TV LED 4K com processador Crystal e sistema operativo Tizen. Equipamento com elevada incidência de reparação de barras de retroiluminação LED e circuitos de alimentação na nossa oficina.',
    specifications: [
      { label: 'Tipo de Painel', value: 'LED UHD 4K 3840 x 2160' },
      { label: 'Alimentação', value: '100-240V ~ 50/60Hz bivolt' },
      { label: 'Tecnologia de Retroiluminação', value: 'Edge LED / Direct LED' },
      { label: 'Serviço Ama Tec Associado', value: 'Reparação de Televisores' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/samsung-55.jpg (Fotografia real pendente)',
    relatedModels: ['lg-nanocell-55', 'tcl-qled-50'],
  },
  {
    id: 'eq-tv-lg-55',
    slug: 'lg-nanocell-55',
    name: 'Televisor LG NanoCell 55"',
    brand: 'LG',
    model: 'NanoCell 4K (Série NANO)',
    category: 'domestico',
    categoryName: 'Linha Doméstica',
    serviceSlug: 'reparacao-de-televisores',
    description: 'Smart TV de alta fidelidade cromática equipada com sistema webOS. Assistência especializada em substituição de kit de LED original e reparação de placa de fonte SMPS.',
    specifications: [
      { label: 'Resolução', value: '4K Ultra HD com tecnologia NanoCell' },
      { label: 'Processador de Imagem', value: 'α5 AI Processor' },
      { label: 'Consumo Médio', value: '145W em operação padrão' },
      { label: 'Serviço Ama Tec Associado', value: 'Reparação de Televisores' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/lg-55.jpg (Fotografia real pendente)',
    relatedModels: ['samsung-crystal-uhd-55'],
  },
  {
    id: 'eq-lav-samsung-ecobubble',
    slug: 'samsung-ecobubble-8kg',
    name: 'Máquina de Lavar Roupa Samsung EcoBubble 8kg',
    brand: 'Samsung',
    model: 'EcoBubble Digital Inverter 8kg',
    category: 'domestico',
    categoryName: 'Linha Doméstica',
    serviceSlug: 'reparacao-de-maquinas-de-lavar',
    description: 'Máquina de lavar de carregamento frontal com motor Digital Inverter. Assistência frequente para desbloqueio de bomba de drenagem, troca de amortecedores e substituição do módulo eletrónico de comando.',
    specifications: [
      { label: 'Capacidade de Carga', value: '8 kg de roupa seca' },
      { label: 'Tecnologia do Motor', value: 'Digital Inverter sem correia direta' },
      { label: 'Velocidade de Centrifugação', value: 'Até 1400 RPM' },
      { label: 'Serviço Ama Tec Associado', value: 'Reparação de Máquinas de Lavar' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/samsung-ecobubble.jpg (Fotografia real pendente)',
    relatedModels: ['lg-directdrive-9kg'],
  },
  {
    id: 'eq-lav-lg-directdrive',
    slug: 'lg-directdrive-9kg',
    name: 'Máquina de Lavar LG AI DD 9kg',
    brand: 'LG',
    model: 'AI DD Inverter Direct Drive 9kg',
    category: 'domestico',
    categoryName: 'Linha Doméstica',
    serviceSlug: 'reparacao-de-maquinas-de-lavar',
    description: 'Equipamento topo de gama com sensor inteligente de tecidos. Reparação de placas controladoras inverter, sensores de efeito Hall e bombas de evacuação.',
    specifications: [
      { label: 'Capacidade', value: '9 kg lavagem' },
      { label: 'Motor', value: 'Inverter Direct Drive com acoplamento direto' },
      { label: 'Classe de Isolamento', value: 'Proteção IPX4' },
      { label: 'Serviço Ama Tec Associado', value: 'Reparação de Máquinas de Lavar' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/lg-directdrive.jpg (Fotografia real pendente)',
    relatedModels: ['samsung-ecobubble-8kg'],
  },
  {
    id: 'eq-airfryer-philips-xxl',
    slug: 'philips-airfryer-xxl',
    name: 'Fritadeira sem Óleo Philips Walita Airfryer XXL',
    brand: 'Philips',
    model: 'Airfryer XXL Twin TurboStar',
    category: 'domestico',
    categoryName: 'Linha Doméstica',
    serviceSlug: 'reparacao-de-air-fryer',
    description: 'Airfryer de alta potência térmica. Reparação comum de fusíveis de proteção térmica, substituição de resistências blindadas e calibração de sensores NTC.',
    specifications: [
      { label: 'Potência Nominal', value: '2225 W' },
      { label: 'Capacidade do Cesto', value: '1.4 kg / 7.3 Litros' },
      { label: 'Gama de Temperatura', value: '40°C a 200°C' },
      { label: 'Serviço Ama Tec Associado', value: 'Reparação de Air Fryer' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/philips-xxl.jpg (Fotografia real pendente)',
    relatedModels: ['ninja-dualzone-af300'],
  },
  {
    id: 'eq-micro-panasonic-inverter',
    slug: 'panasonic-inverter-32l',
    name: 'Forno Micro-ondas Panasonic Inverter 32L',
    brand: 'Panasonic',
    model: 'Inverter Turbo Defrost 32L',
    category: 'domestico',
    categoryName: 'Linha Doméstica',
    serviceSlug: 'reparacao-de-micro-ondas',
    description: 'Micro-ondas com tecnologia de potência contínua Inverter (sem transformador convencional). A Ama Tec repara placas de fonte chaveada inverter de alta frequência e magnetrões originais.',
    specifications: [
      { label: 'Potência Micro-ondas', value: '1000 W contínuos reguláveis' },
      { label: 'Volume Útil', value: '32 Litros' },
      { label: 'Circuito Gerador', value: 'Módulo Inverter de Alta Tensão' },
      { label: 'Serviço Ama Tec Associado', value: 'Reparação de Micro-ondas' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/panasonic-inverter.jpg (Fotografia real pendente)',
    relatedModels: ['philips-airfryer-xxl'],
  },
  {
    id: 'eq-forno-racional-combi',
    slug: 'forno-combinado-industrial-6gn',
    name: 'Forno Combinado Industrial 6 GN 1/1',
    brand: 'Equipamento de Restauração Comercial',
    model: 'Forno de Convecção e Vapor 6 GN',
    category: 'industrial',
    categoryName: 'Industrial e Comercial',
    serviceSlug: 'cozinhas-industriais',
    description: 'Equipamento essencial de cozinhas industriais para panificação e restauração coletiva. Reparação de resistências trifásicas, bombas dosadoras e comandos eletrónicos digitais.',
    specifications: [
      { label: 'Alimentação Elétrica', value: '380V - 415V 3N~ 50/60Hz (Trifásico)' },
      { label: 'Capacidade', value: '6 tabuleiros GN 1/1' },
      { label: 'Potência de Ligação', value: '11 kW' },
      { label: 'Serviço Ama Tec Associado', value: 'Assistência a Cozinhas Industriais' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/forno-industrial.jpg (Fotografia real pendente)',
    relatedModels: ['balanca-checkout-toledo'],
  },
  {
    id: 'eq-balanca-toledo',
    slug: 'balanca-checkout-toledo',
    name: 'Balança Eletrónica Comercial de Checkout',
    brand: 'Linha Comercial',
    model: 'Balança de Pesagem com Interface Série RS232',
    category: 'industrial',
    categoryName: 'Industrial e Comercial',
    serviceSlug: 'balancas-pos-comercial',
    description: 'Balança de balcão e supermercado para integração com sistemas de faturação e POS. Calibração de célula de carga e reparação de circuitos conversores A/D.',
    specifications: [
      { label: 'Capacidade Máxima', value: '15 kg / Divisão de 5g' },
      { label: 'Interface de Dados', value: 'RS-232C e USB padrão de checkout' },
      { label: 'Display', value: 'Duplo display operador e cliente' },
      { label: 'Serviço Ama Tec Associado', value: 'Balanças Eletrónicas & POS' },
    ],
    photoPlaceholder: 'TODO_CONTEUDO: /public/images/equipamentos/balanca-comercial.jpg (Fotografia real pendente)',
    relatedModels: ['forno-combinado-industrial-6gn'],
  },
];
